apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurora-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aurora-postgres
  template:
    metadata:
      labels:
        app: aurora-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_PASSWORD
          value: "fortworth"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: aurora-postgres-service
spec:
  selector:
    app: aurora-postgres
  ports:
    - port: 5432
      targetPort: 5432
